services:
  - type: web
    name: code-nexus
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000  # Render will auto-assign a port, so this is optional
